### ISSUE TITLE
Error updating nsd when manually edited (without refresh)

### ISSUE THREAD

**Issue by GeoMSK** [kasimoglou/netsim#44]
Steps to reproduce:
1. create an NSD using the GUI
2. keep the NSD editor open
3. manually modify the NSD in couchDB
4. return to the NSD editor and try to save again
5. "Error updating nsd"

**Note: if we refresh the NSD editor's page it successfully saves it**

Is there a use case where this is a problem?

**Comment by kasimoglou** [comment]
When you update a record in CouchDb, `_rev` field gets updated. In order to save again you have to enclose to your update the most recent `_rev`.
So you open an Nsd in editor, let's say its `_rev = a`. When you manually update nsd in couchdb `_rev` gets let's say `b`. You go back to editor where `_rev` is still `a` and you try to save. Couch db will complain.
If you refresh Editor, nsd is returned with its new `_rev` that's why you are able to save again.
@vsamtuc @GeoMSK @jvlahou Is that a real case we should handle?

**Comment by kasimoglou** [comment]
Fixed in #20.
