### ISSUE TITLE
The second consecutive update in a plot using the GUI is not reflected to the database

### ISSUE THREAD

**Issue by GeoMSK** [kasimoglou/netsim#45]
Steps to reproduce:
1. open a nsd file using the nsd editor
2. in the output tab click on a view
3. click edit on a plot of that view
4. change something and click update
5. save the nsd
6. click edit on the same or some other plot of that view
7. change something and click update
8. save the nsd

The second change is not saved in the database. Check in couchDB or close the nsd editor and reopen that nsd.

**Comment by GeoMSK** [comment]
workaround: refresh the page before making changes and save

**Comment by kasimoglou** [comment]
The problem occurs because when we update nsd, existing nsd is replaced from the response object (it's the new updated project). 
Now where the problem was. In order to keep track which view user has selected, when user clicks a view row I store `view` object to a `selected_view` object. Then I was using `selected_view` in order to access selected view's plots, update them, etc.
When nsd was saved, as I said, `nsd` object was replaced. So each `view` in nsd comes now from a new object, and `selected_view` no longer 'points' to an existing view object, so any changes made to that object are not reflected to nsd.
Solution: When user selects a view row, I store `view`'s `index` rather that view itself, and I access the view through its index (if user has not selected any view default selected view is the one with index 0). So even if the nsd changes, when I need `selected_view` I will always get the right object.

Good catch @GeoMSK !
